version: '3.8'
services:
    app1:
        container_name: app1
        hostname: app1
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./app1:/var/www/html/
        ports:
            - "5001:80"
    app2:
        container_name: app2
        hostname: app2
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./app1:/var/www/html/
        ports:
            - "5002:80"
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"
    nginx:
        build: ./nginx
        ports:
            - "8080:80"
        depends_on:
            - app1
            - app2
