version: '3.8'
services:
    app1:
        container_name: app1
        hostname: app1
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./myapp/static/controlRoom:/var/www/html/
        ports:
            - "5001:80"
    app2:
        container_name: app2
        hostname: app2
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./myapp:/var/www/html/
        ports:
            - "5002:80"

    db:
        container_name: db
        image: mariadb:10.3
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: notSecureChangeMe
        volumes:
            - ./data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
        - 8888:80
        environment:
        - PMA_ARBITRARY=1

    track:
        container_name: track
        hostname: track
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/
        ports:
            - "5050:80"

    nginx:
        build: ./nginx
        ports:
            - "8080:80"
        depends_on:
            - app1
            - app2
    api:
        build: ./myapp/node.js
        environment:
            NODE_ENV: production
        restart: always
